name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.3.app

    - name: Build and test
      run: xcodebuild clean build test -project ActionsTest.xcodeproj -scheme "ActionsTest" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
